_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.11
            "5": 0.18.7
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
clip_range:
    value: 0.22764966788337368
ent_coef:
    value: 1.0069523197061572
gamma:
    value: 0.935
learning_rate:
    value: 1.0006558249534832
n_steps:
    value: 500
